spring:
  application:
    name: candidate-service
  jackson:
    property-naming-strategy: SNAKE_CASE
  datasource:
    url: jdbc:mysql://localhost:3306/candidate-service?useSSL=false&allowPublicKeyRetrieval=true
    username: toor
    password: toor
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 100
      minimum-idle: 10
      idle-timeout: 30000
      max-lifetime: 1800000
      connection-timeout: 30000
      validation-timeout: 5000
      leak-detection-threshold: 2000

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
        show_sql: false
        jdbc:
          batch_size: 50
          fetch_size: 50

  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true

server:
  undertow:
    max-http-threads: 200 # Número máximo de hilos para manejar solicitudes HTTP
    min-http-threads: 10   # Número mínimo de hilos para manejar solicitudes HTTP
    buffer-size: 16384      # Tamaño del búfer en bytes (16 KB)
    direct-buffers: true    # Usar búferes directos para mejorar el rendimiento
    io-threads: 10           # Número de hilos de entrada/salida
    max-connections: 1000    # Número máximo de conexiones simultáneas
    max-post-size: 10485760  # Tamaño máximo para las solicitudes POST (10 MB)
  connection-timeout: 30s   # Tiempo de espera para la conexión
  request-timeout: 30s       # Tiempo máximo para manejar una solicitud
  error:
    include-stacktrace: always
    include-message: always